const characterProperties = {
  base: {
    name: "base",
    path: `/cozy-people-asset-pack/0-base/`,
    files: ["char_all.png"],
    colors: ["1", "2", "3", "4", "5", "6", "7", "8"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  eyes: {
    name: "eyes",
    path: `/cozy-people-asset-pack/1-eyes/`,
    files: ["eyes.png"],
    colors: [
      "brown",
      "teal",
      "blue",
      "maroon",
      "grey",
      "russet",
      "green",
      "dark green",
      "light green",
      "black",
      "white",
      "red",
      "pink",
      "orange",
    ],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  blush: {
    name: "blush",
    path: `/cozy-people-asset-pack/2-blush/`,
    files: ["blush_all.png"],
    colors: ["1", "2", "3", "4", "5"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  lipstick: {
    name: "lipstick",
    path: `/cozy-people-asset-pack/3-lipstick/`,
    files: ["lipstick.png"],
    colors: ["1", "2", "3", "4", "5"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  upper: {
    name: "upper",
    path: `/cozy-people-asset-pack/4-upper/`,
    files: [
      "basic.png",
      "floral.png",
      "sailor_bow.png",
      "sporty.png",
      "stripe.png",
      "suit.png",
    ],
    colors: [
      "black",
      "blue",
      "brown",
      "cyan",
      "green",
      "pink",
      "purple",
      "red",
      "white",
    ],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  lower: {
    name: "lower",
    path: `/cozy-people-asset-pack/5-lower/`,
    files: ["dress.png", "pants_suit.png", "pants.png", "skirt.png"],
    colors: [
      "black",
      "blue",
      "brown",
      "cyan",
      "green",
      "pink",
      "purple",
      "red",
      "white",
    ],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  bodysuit: {
    name: "bodysuit",
    path: `/cozy-people-asset-pack/6-bodysuit/`,
    files: [
      "clown.png",
      "overalls.png",
      "pumpkin.png",
      "sailor.png",
      "skull.png",
      "spaghetti.png",
      "spooky.png",
      "witch.png",
    ],
    colors: ["blue", "red"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  shoes: {
    name: "shoes",
    path: `/cozy-people-asset-pack/7-shoes/`,
    files: ["shoes.png"],
    colors: ["1"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  hair: {
    name: "hair",
    path: `/cozy-people-asset-pack/8-hair/`,
    files: [
      "bob.png",
      "braids.png",
      "buzzcut.png",
      "curly.png",
      "emo.png",
      "extra_long_skirt.png",
      "extra_long.png",
      "french_curl.png",
      "gentleman.png",
      "long_straight.png",
      "long_straight_skirt.png",
      "midiwave.png",
      "ponytail.png",
      "spacebuns.png",
      "wavy.png",
    ],
    colors: [
      "black",
      "blonde",
      "brown",
      "maroon",
      "orange",
      "turquoise",
      "green",
      "grey",
      "purple",
      "blue",
      "pink",
      "dark purple",
      "red",
      "cyan",
    ],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  beard: {
    name: "beard",
    path: `/cozy-people-asset-pack/9-beard/`,
    files: ["beard.png"],
    colors: [
      "brown",
      "blonde",
      "maroon",
      "light grey",
      "orange",
      "cyan",
      "green",
      "grey",
      "magenta",
      "purple",
      "pink",
      "dark blue",
      "red",
      "teal",
    ],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  glasses: {
    name: "glasses",
    path: `/cozy-people-asset-pack/a-glasses/`,
    files: ["glasses.png", "glasses_sun.png"],
    colors: [
      "black",
      "lead",
      "blue",
      "brown",
      "slate",
      "green",
      "pink",
      "purple",
      "red",
      "grey",
    ],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  earring: {
    name: "earring",
    path: `/cozy-people-asset-pack/b-earring/`,
    files: [
      "earring_emerald_silver.png",
      "earring_emerald.png",
      "earring_red_silver.png",
      "earring_red.png",
    ],
    colors: ["1"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  hat: {
    name: "hat",
    path: `/cozy-people-asset-pack/c-hat/`,
    files: [
      "hat_cowboy.png",
      "hat_lucky.png",
      "hat_pumpkin_purple.png",
      "hat_pumpkin.png",
      "hat_witch.png",
    ],
    colors: ["1"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  mask: {
    name: "mask",
    path: `/cozy-people-asset-pack/d-mask/`,
    files: ["mask_clown_blue.png", "mask_clown_red.png", "mask_spooky.png"],
    colors: ["1"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
};

export default characterProperties;
