const characterProperties = {
  base: {
    name: "base",
    path: `0-base`,
    files: [
      "char1.png",
      "char2.png",
      "char3.png",
      "char4.png",
      "char5.png",
      "char6.png",
      "char7.png",
      "char8.png",
    ],
    colors: ["1"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  eyes: {
    name: "eyes",
    path: `1-eyes`,
    files: ["eyes.png"],
    colors: [
      "brown",
      "teal",
      "blue",
      "maroon",
      "grey",
      "russet",
      "green",
      "dark green",
      "light green",
      "black",
      "white",
      "red",
      "pink",
      "orange",
    ],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  blush: {
    name: "blush",
    path: `2-blush`,
    files: ["blush.png"],
    colors: ["1", "2", "3", "4", "5"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  lipstick: {
    name: "lipstick",
    path: `3-lipstick`,
    files: ["lipstick.png"],
    colors: ["1", "2", "3", "4", "5"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  upper: {
    name: "upper",
    path: `4-upper`,
    files: [
      "basic.png",
      "floral.png",
      "sailor_bow.png",
      "sporty.png",
      "stripe.png",
      "suit.png",
      "overalls.png",
    ],
    colors: [
      "black",
      "cyan",
      "blue",
      "brown",
      "hazel",
      "green",
      "pink",
      "purple",
      "red",
      "white",
    ],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  lower: {
    name: "lower",
    path: `5-lower`,
    files: ["dress.png", "pants_suit.png", "pants.png", "skirt.png"],
    colors: [
      "black",
      "cyan",
      "blue",
      "brown",
      "hazel",
      "green",
      "pink",
      "purple",
      "red",
      "white",
    ],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  bodysuit: {
    name: "bodysuit",
    path: `6-bodysuit`,
    files: ["clown.png", "pumpkin.png", "spooky.png", "witch.png"],
    colors: ["1"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  shoes: {
    name: "shoes",
    path: `7-shoes`,
    files: ["shoes.png"],
    colors: [
      "black",
      "cyan",
      "blue",
      "brown",
      "hazel",
      "green",
      "pink",
      "purple",
      "red",
      "white",
    ],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  hair: {
    name: "hair",
    path: `8-hair`,
    files: [
      "bob.png",
      "braids.png",
      "buzzcut.png",
      "curly.png",
      "emo.png",
      "extra_long.png",
      "french_curl.png",
      "gentleman.png",
      "long_straight.png",
      "midiwave.png",
      "ponytail.png",
      "spacebuns.png",
      "wavy.png",
    ],
    colors: [
      "black",
      "blonde",
      "brown",
      "maroon",
      "orange",
      "turquoise",
      "green",
      "grey",
      "purple",
      "blue",
      "pink",
      "dark purple",
      "red",
      "cyan",
    ],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  beard: {
    name: "beard",
    path: `9-beard`,
    files: ["beard.png"],
    colors: [
      "brown",
      "blonde",
      "maroon",
      "light grey",
      "orange",
      "cyan",
      "green",
      "grey",
      "magenta",
      "purple",
      "pink",
      "dark blue",
      "red",
      "teal",
    ],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  glasses: {
    name: "glasses",
    path: `a-glasses`,
    files: ["glasses.png", "glasses_sun.png"],
    colors: [
      "black",
      "lead",
      "blue",
      "brown",
      "slate",
      "green",
      "pink",
      "purple",
      "red",
      "grey",
    ],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  earring: {
    name: "earring",
    path: `b-earring`,
    files: [
      "earring_emerald_silver.png",
      "earring_emerald.png",
      "earring_red_silver.png",
      "earring_red.png",
    ],
    colors: ["1"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  hat: {
    name: "hat",
    path: `c-hat`,
    files: [
      "hat_cowboy.png",
      "hat_lucky.png",
      "hat_pumpkin_purple.png",
      "hat_pumpkin.png",
      "hat_witch.png",
    ],
    colors: ["1"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
  mask: {
    name: "mask",
    path: `d-mask`,
    files: ["mask_clown_blue.png", "mask_clown_red.png", "mask_spooky.png"],
    colors: ["1"],
    frameSize: {
      x: 32,
      y: 32,
      xSpace: 0,
      ySpace: 0,
    },
  },
};

export default characterProperties;
